version: '3'
services:
  mhw-nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: nginx -g "daemon off;"
    links:
      - mhw-php
    ports:
      - '8989:80'
    networks:
      - sail
  mhw-php:
      build:
          context: ./docker/php
          dockerfile: Dockerfile
          args:
              WWWGROUP: '${WWWGROUP}'
      image: sail-8.0/app
      ports:
          - '${APP_PORT:-9000}'
      environment:
          WWWUSER: '${WWWUSER}'
          LARAVEL_SAIL: 1
      volumes:
          - '.:/var/www/html'
      networks:
          - sail
networks:
    sail:
        driver: bridge
