name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.0'

    - uses: actions/checkout@v2

    - name: "Validate composer.json and composer.lock"
      run: "composer validate --strict"

    - name: "Determine composer cache directory"
      id: "determine-composer-cache-directory"
      run: "echo \"::set-output name=directory::$(composer config cache-dir)\""

    - name: "Cache dependencies installed with composer"
      uses: "actions/cache@v2.0.0"
      with:
        path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
        key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
        restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Statically analyse code via PHPStan
      run: ./vendor/bin/phpstan analyse --memory-limit=1G

    - name: Check coding standard violations via PHPCS
      run: ./vendor/bin/phpcs .

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: ./vendor/bin/phpunit
